### ISSUE TITLE
Provide a template for inlcuding all properties defined in a property yaml file ?

### ISSUE THREAD

**Issue by jessehu** [pivotal-cf/kiln#7] opened 2018-03-11 15:39 UTC
.e.g I have a file properties/form1_properties.yml

name: element_1
type: text
configurable: true
optional: true

name: element_2
type: text
configurable: true
optional: true

name: element_N
type: text
configurable: true
optional: true

Currently, I have to add the following code in base.yml, which is very tedious.

property_blueprints:
- $( property "element_1" )
- $( property "element_2" )
- $( property "element_N" )

Why not allowing this grammar:
property_blueprints:
- $(properties_in "form1_properties")

Or by default "property_blueprints:" reads all properties defined in properties/*.yml ?

Thanks.

**Comment by ryanmoran** [comment] 2018-03-11 18:09
@jessehu you are not required to use the `$( property "element" )` template function. You can just inline all of your product properties. The helper exists so that you can pull especially large properties out into their own files. If you find that that is tedious, then just inline the properties into your metadata file instead of using the helper. Its completely optional.

**Comment by jessehu** [comment] 2018-03-12 02:12
Thanks @ryanmoran. Adding all properties definition directly in metadata base.yml also make base.yml tedious, because all other section in metadata base.yml uses template functions. Usually there are a lot of properties definition comparing to other tile resource definition.

**Comment by ryanmoran** [comment] 2018-03-12 16:17
I'm not gonna say we won't do this, but it is pretty unlikely. The proposed solution leaves a lot up to implicit connections between the metadata file and other files that might contain properties. We built the template functions to be as explicit as possible. To revert back to an implicit policy of just including properties if they appear in a certain location on disk seems like a regression in understandability in my mind.

**Comment by davewalter** [comment] 2018-05-29 21:32
Closing issue due to lack of new activity.

**Closed by davewalter** 2018-05-29 21:32 UTC
Labels: unscheduled
